<!--
---
title: "Data Generation Framework"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data Generation Framework}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, warning=FALSE, message=FALSE, echo=FALSE}
# library(benchtm)
library(tidyverse)
```
In this article, the framework used to generate the subgroup simulation will be provided, along with the prameters used in the data generation process. 

## Data generation framework 
Consider a two-arm study where trt = 0 represent control arm and trt = 1 represents treatment arm, the clinical outcome/response $Y$ is generated from 

\begin{equation}{eq:data-generation-form}
f(X) = f_{prog}(X) + trt*(\beta_0 + \beta_1 f_{pred}(X)),
\end{equation}

while $f_{prog}(X)$ is the function for prognostic variable and $f_{pred}(X)$ is a function for predictive variable; $\beta_0$ and $\beta_1$ are used to control the treatment effect size and standard deviation respectively. $f(X)$ is a function used for generating response $Y$ depending on the type of response considered. For a continuous response, $Y = f(X) + \epsilon$, where $\epsilon \sim N(0, 1)$. For other type of reponses, see Section \@ref(treatment-and-responses).

From the data generation formula one can see that, the larger the $\beta_0$, the more power there is to detect the overall treatment effect; the larger the $\beta_1$, the more likely it is to detect the subgroup (the larger the treatment effect variability). For pre-specified power (to detect treatment effect) and standard deviation of treatment effect, the value of $\beta_0$ and $\beta_1$ can be calculated accordingly. The data is then generated afterwards. The flow chart for generation is presented below:

```{r final_submission_model, warning=FALSE, message=FALSE, echo=FALSE, fig.cap = "Figure 1: Data generation flow", fig.width = 9, fig.height = 2}
tibble(xmin=c(0, 18, 27), xmax=c(14, 23, 34),
       ymin=c(0, 0, 0), ymax=c(1, 1, 1),
       x =    c(14, 23, NA_real_),
       xend = c(18, 27, NA_real_),
       y =    c(0.5, 0.5, NA_real_),
       yend = c(0.5, 0.5, NA_real_),
       grouping=c("a", "a", "a"),
       Description=c("Given:\n- Power, sample size\n- Standard deviation of\n   treatment effect\n- Prognostic and predictive forms", 
                     "Obtain:\n- beta0\n- beta1",
                     "Generate data")) %>%
  ggplot(aes(xmin=xmin, xmax=xmax,
             ymin=ymin, ymax=ymax,
             x=x, y=y, xend=xend, yend=yend,
             label=Description,
             fill=grouping)) +
  geom_rect(alpha=c(0.4, 0.4, 0.4)) +
  geom_segment(arrow = arrow(length = unit(0.2, "cm"), type="closed")) +
  geom_text(aes(x=xmin+1, y=ymin+0.2), size= 5,
            hjust = c(rep(0.01,3)),
            vjust=c(0.1, -0.1, -3),
            angle=c(0,0,0)) +
  scale_fill_brewer(type="qual", palette="Dark2") +
  theme_classic(base_size=18) +
  theme(legend.position = "none",
        axis.title = element_blank(),
        axis.line =  element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


## Parameters considered

In the data generation, there are different parameters considered. They are presented in the table below:

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
data.frame(
  Parameters = c("Sample Size", "Number of Predictors", "Power (determining treatment effect size)", "Standard deviation of treatment effect", "Treatment effect structure","Number of variables defining subgroup", "Clinical endpoints"),
  Settings = c("100, 500, 1000", "30, 100", "0.05, 0.50, 0.90","small, medium, large", "step, linear", "0, 1, 2", "continuous, binary, count, survival")
) %>% 
  mutate(Parameters = cell_spec(Parameters, bold = T)) %>%
  kable(format = "html", escape = F) %>%
  kable_styling("striped", full_width = T, font_size = 12)
```

For sample size options, we considered commonly settings for a phase II (around 100) and phase III trial (500 - 1000), a power of 90% was uauslly considered before set up clinical trials, as a comparison, a power of 50% (medium) and 0.05 (no treatment effect) are also considered. 

## Treatment and responses{treatment-and-responses}
For this project, the focus is on two-arm study where only two treatment are considered. For the data generation framework, we consider $P(trt = 1|X) = 1/1+exp(-prop(X))$ where $prop(X)$ is a user specified form. When $prop(X) = 0$, $P(trt = 1|X) = 0.5$ represents a setting for complete randomized design. See more details in [user guide](http://shinyserver-r361.statwb.eu.novartis.net/sunhud/benchtm/docs/articles/Examples.html).

Depending on different types of responses and the form \@ref(eq:data-generation-form) to generate response, the clinical endpoints are generated from 

- Continuous response: $Y \sim N(\mu = f(X), \sigma)$
- Binary response: $Y \sim \text{Bernoulli}(logit(p) = f(X))$
- Count response: $Y\sim \text{Poisson}(log(\lambda) = f(X))$
- Time to event: $t\sim \text{Exponential}(log(\lambda) = f(X))$

## Some technical details

This section provide some details on the definition of standard deviation of treatment effect and the calculation of power.

### Definition of standard deviation of treatment effect 
In our data generation framework, the standard deviation of treatment effect is defined as $sd\_te = sd(\beta_0 + \beta_1*pred) = \beta_1*sd(pred)$. Note that sd_te is only related with predictive variables and $\beta_1$, and it has different meanings under different response types.

- Continuous response: $$sd\_te = sd(\mu_1 - \mu_0),$$ where $\mu_1 = f(X|trt = 1)$ and $\mu_0 = f(X|trt = 0)$. Sd_te is defined as the standard deviation of treatment effect.
- Binary response: $$sd\_te = sd(log\frac{Odds(p_1))}{Odds(p_0)}),$$ where $p_1 = P(Y = 1|trt = 1)$ and $p_0 = P(Y = 1|trt = 0)$. Sd_te is defined as the standard deviation of log odds ratio.
- Count/time to event response: $$sd\_te = sd(log\frac{\lambda_1}{\lambda_0}),$$ where $\lambda_1 = f(X|trt = 1)$ and $\lambda_0 = f(X|trt = 0)$. Sd_te is defined as the standard deviation of the log rate ratio.

### Calculation of power
The power is the ability to dectect overall treatment effect between treatment and control group. It is based on a two sided test with significant level $\alpha = 0.05$. The power is calculated as in below:

- For continuous response: $$power = \Phi(z - Z_{1-\alpha/2}) +\Phi(-z - Z_{1-\alpha/2})$$ where $z = \frac{\mu_1-\mu_0}{\sqrt{2(\sigma_1^2+\sigma_0^2)/n}}$ and $n$ is the total sample size. $\mu_1, \mu_0$ and $\sigma$ are estimated from a very large sample with size $N = 50,000$
- For binary response: $$power = \Phi(z - Z_{1-\alpha/2}) +\Phi(-z - Z_{1-\alpha/2})$$ where $z = \frac{p_1-p_0}{\sqrt{p_1(1-p_1)/n_1 + p_0(1-p_0)/n_0}}$, $n_1 = n_0 = n/2$. Both $p_0$ and $p_1$ are estimated from a very large sample with size $N = 50,000$.
- For count/time to event response: Fit model (based on sample with size N = 50,000) $$log(\lambda) = \beta_0^*+\beta_1^*trt$$ using negative binomial/cox hazrd model, get the estimation of trt coefficient and its standard deviation, power is calculated based on the approximate normal distribution of treatment coefficient. $$power = \Phi(z - Z_{1-\alpha/2}) +\Phi(-z - Z_{1-\alpha/2})$$ where $z = \hat{\beta_1^*}/sd(\hat{\beta_1^*})$.

The power calculation for continuous response is based on the t distribution of the estimated overall treatment effect. For binary response, the power calculation is based on the approximate normal distribution of the proportion difference. For count and time to event reponse, the power calculation is based on the approximated normal distribution of treatment effect estimation for negative binomial and cox hazard models respectively.


-->
