<!--
---
title: "Original Clinical Trial Data and Data 'syn' Comparison"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data 'syn'}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

To inlude the setting which is close to the real data, data "syn" is generated from a phase III clinical trial data. R package ["synthpop"](https://cran.r-project.org/web/packages/synthpop/index.html) is used for the data "syn" generation. For the interest of patient information confidentiality, column names of data "syn" have been transformed into $X_1, X_2, ...X_{30}$, the levels for the categorical variables has been renamed, and the continuous variable has been rescaled. However, for the comparison purpose, in this article, the comparison are based on the data 'syn' before renaming and scaling.

## Original clinical trial data description

The original trial data includes 30 predictor and 1947 patients (after preprocessing), they are 

- patient demographic information (AGE, SEX, BMI, ethnic ...)
- patient disease history information (time of PsA, usage of other treatment ...)
- patient disease activities at baseline (PASDAS at baseline, HAQDI at baseline  ...) 
 
A description of the parameters considered at baseline is in the table below:

A snip of the data description is presented below： 
```{r, echo=FALSE, message=FALSE, warning = FALSE}
suppressPackageStartupMessages(library(synthpop))
suppressPackageStartupMessages(library(dplyr))
# suppressPackageStartupMessages(library(tidyverse))
# suppressPackageStartupMessages(library(partykit))
# suppressPackageStartupMessages(library(Hmisc))
suppressPackageStartupMessages(library(PerformanceAnalytics))
library(knitr)
library(kableExtra)
library(readxl)
data_orig = readRDS("/home/sunhud/Projects/benchtm/source_data/clean_data.rds")
data_orig <- data_orig %>% mutate_if(is.factor, as.character) %>% data.frame()

## variable description
# Specify sheet by its name
data_desp <- read_excel("/home/sunhud/Projects/benchtm/source_data/CodeBook_v3.xlsx", sheet = "baseline_cosentyx")
data_desp %>% filter(variable %in% colnames(data_orig)) %>%
  arrange(variable)%>%
  kable(caption = "Table 1: The description of original variables for data 'syn'") %>%
  kable_styling(font_size = 12) %>%
  scroll_box(width = "100%", height = "250px")
```

To check out the similarity of the raw data and synthetic data, we did some comparison for both marginal and joint distributions. 

## Marginal distribution comparison of raw and synthetic data
To better understand the marginal distribution for data 'syn', the marginal distribution for both trial data are data 'syn' are presented in Figure 1.
```{r, echo=FALSE, message=FALSE, warning = FALSE, fig.cap="Figure1: Marginal distribution comparison for original trial data and data 'syn'"}
# synthesise data simple
synth.obj <- synthpop::syn(data_orig, seed = 2020, print.flag = FALSE)
tmp_plot <- compare(synth.obj, data_orig, nrow = 2, ncol = 4, print.flag = FALSE)$plot
tmp_plot[[1]]
tmp_plot[[2]]
tmp_plot[[3]]
tmp_plot[[4]]

```

As presented in Figure 1, the marginal distribution plot of trial data and data 'syn' looks very similar to each other.

## Correlation comparision for continuous variables 
The correlations of the two data for the continous covariates are given in Figure 2 and Figure 3 to better understand the dependencies of the covariates.

```{r, echo=FALSE, message=FALSE, fig.cap="Figure 2: Correlation for continuous variables for original data"}
### continous correlation
chart.Correlation(as.matrix(data_orig %>% dplyr::select(SF36BP:TNJT28)), histogram=TRUE, pch=19)
```

```{r, echo=FALSE, message=FALSE, warning = FALSE, fig.cap="Figure 3: Correlation for continuous variables for data 'syn'"}
chart.Correlation(as.matrix(synth.obj$syn %>% dplyr::select(SF36BP:TNJT28)), histogram=TRUE, pch=19)
```

To better compare the difference between the correlations, the correlation for pairwise continuous covariates for trial data and data "syn" are presented in Figure 4.

```{r, echo=FALSE, message=FALSE, warning = FALSE, fig.cap="Figure 4: Pairwise correlation comparison for continuous variables for between trial data and data 'syn', the red line is y = x"}
library(Hmisc)
library(ggplot2)
cor_syn <- rcorr(as.matrix(synth.obj$syn %>% dplyr::select(SF36BP:TNJT28)), type="pearson") # type can be pearson or spearman
cor_orig <- rcorr(as.matrix(data_orig %>% dplyr::select(SF36BP:TNJT28)), type="pearson") # type can be pearson or spearman

cor_plot <- data.frame(syn = as.vector(cor_syn$r), orig = as.vector(cor_orig$r))
ggplot(cor_plot, aes(orig, syn)) + geom_point(color = "blue") + 
  theme_bw() + geom_abline(intercept = 0, slope = 1, color = "red") + 
  xlab("Original trial data") + ylab("Data 'syn'") + ggtitle("Pairwise correlation relationship")
```

The correlation matrix for contious variables in two data sets looks very similar to each other, indicating the reservation of the dependency for continuous covariates for synethetic data generation.

## Some selected comparisons consider interactions
To better understand the joint distribution, some comparisons for categorical/continuous data with interactions are also presented in Figure 5.
```{r, echo=FALSE, message=FALSE, warning = FALSE, fig.cap="Figure 5: Correlation for categorical variables for trial data and data 'syn'."}
### categorical var
synthpop::multi.compare(synth.obj, data_orig, var = "SEX", by = c("GREGGR1","DACTFL"))
### compare values with interaction
synthpop::multi.compare(synth.obj, data_orig,  var = "BMI", by = c("SEX"), y.hist = "density", binwidth = 5)
synthpop::multi.compare(synth.obj, data_orig,  var = "BMI", by = c("SEX", "ENTHFL"), cont.type = "boxplot")
```

-->
